#!/usr/bin/env python3
"""Assert counts asserted in documentation match the counts asserted in source.

Docs said "23 extension surfaces" in six places while `uni_plugin::surfaces`
asserts `assert_eq!(kinds.len(), 22)`. The structural fact was already pinned in
code — the prose simply was not wired to it. The same shape recurred in every
other family anyone had counted by hand: `uni-tck/README.md` claimed 220 feature
files (221 on disk) and 1,339 scenarios while *the same file* reported 3,926 a
hundred lines later; `complete_locy.md` claimed 37/273 for a Locy suite that is
70/501; `ai-skill.md` claimed 8 skill reference files against 12; and the docs
landing page, the pitch and the Black Book claimed 36, 36 and 35 graph
algorithms respectively, none of which was 42.

This wires them. Every check reads its ground truth from something that is
already true independently of the prose — a source assertion, or the filesystem
— so adding a surface, a feature file, a reference page or an algorithm fails
here until the docs are updated, rather than silently drifting.

Adding a check: append a `Check` to `CHECKS`. `truth` returns the number,
`pattern` matches doc claims with the number in group 1 (or the first non-None
group). Prefer a source assertion over a filesystem count when one exists — a
literal in a test is itself gated by that test running.

Historical, dated documents (release notes, `docs/proposals/**`, `docs/plans/**`)
are excluded: they record what was true when published and must not be rewritten.

Exit code 0 = consistent, 1 = drift.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Pattern

ROOT = Path(__file__).resolve().parents[2]

# Directories whose contents are dated records, not live documentation.
EXCLUDED_PARTS = ("release_notes", "proposals", "plans", "archive")

# `crates` is included for the per-crate READMEs (uni-tck's counts live there).
# Only `*.md` is scanned, so the source tree itself is not touched.
DOC_ROOTS = ("website/docs", "docs", "skills", "crates")


def _read(rel: str) -> str:
    return (ROOT / rel).read_text()


def _literal(rel: str, pattern: str) -> int:
    """Extract a single integer pinned by an assertion or const in source."""
    m = re.search(pattern, _read(rel))
    if not m:
        raise SystemExit(
            f"could not find the count assertion in {rel} using {pattern!r}; "
            "update this script if the assertion moved or was renamed"
        )
    return int(m.group(1))


def surface_count() -> int:
    return _literal(
        "crates/uni-plugin/src/surfaces/mod.rs",
        r"assert_eq!\(\s*kinds\.len\(\),\s*(\d+)\s*\)",
    )


def graph_algorithm_count() -> int:
    return _literal(
        "crates/uni-plugin-builtin/tests/builtin_register.rs",
        r"const DISTINCT_ALGORITHMS: usize = (\d+);",
    )


def tck_feature_file_count() -> int:
    return len(list((ROOT / "crates/uni-tck/tck/features").rglob("*.feature")))


_SCENARIO_HEAD = re.compile(
    r"^(Scenario|Scenario Outline|Scenario Template|Background|Rule|Feature):"
)
_EXAMPLES_HEAD = re.compile(r"^(Examples|Scenarios):")


def _scenario_count(root: str) -> int:
    """Scenario total, computed by expanding the `.feature` files themselves.

    Deliberately NOT read from `compliance_reports/*/last_run_report.md`. Those
    are dated artifacts regenerated by hand: at the time this check was written
    the Locy report said 501 while the harness ran 519 — an 18-scenario drift
    that would have made this gate "correct" the docs to a stale number. The
    feature files are the harness's actual input, so they cannot go stale.

    A `Scenario:` is one. A `Scenario Outline:` is one per Examples data row
    (the first pipe row of each Examples block is the header). Verified against
    both live harnesses: openCypher 3926, Locy 519.
    """
    total = 0
    for path in sorted((ROOT / root).rglob("*.feature")):
        lines = path.read_text(errors="ignore").splitlines()
        i = 0
        while i < len(lines):
            stripped = lines[i].strip()
            if stripped.startswith(("Scenario Outline:", "Scenario Template:")):
                j = i + 1
                while j < len(lines):
                    cur = lines[j].strip()
                    if _SCENARIO_HEAD.match(cur):
                        break
                    if _EXAMPLES_HEAD.match(cur):
                        k = j + 1
                        header_seen = False
                        while k < len(lines):
                            row = lines[k].strip()
                            if row.startswith("|"):
                                if header_seen:
                                    total += 1
                                else:
                                    header_seen = True
                            elif row and not row.startswith("#"):
                                break
                            k += 1
                        j = k
                        continue
                    j += 1
                i = j
                continue
            if stripped.startswith("Scenario:"):
                total += 1
            i += 1
    return total


def tck_scenario_count() -> int:
    return _scenario_count("crates/uni-tck/tck/features")


def locy_tck_scenario_count() -> int:
    return _scenario_count("crates/uni-locy-tck")


def locy_tck_feature_file_count() -> int:
    return len(list((ROOT / "crates/uni-locy-tck").rglob("*.feature")))


def skill_reference_count() -> int:
    return len(list((ROOT / "skills/uni-db/references").glob("*.md")))


# Shared between the two TCK suites; which totals they are graded against is
# decided by `Check.paths`, not by the pattern.
FEATURE_FILES = re.compile(r"\b([\d,]{2,6})\s+(?:TCK\s+M\d+\s+)?feature\s+files\b", re.I)
# `(?<![/\d]\s)` keeps "3925 / 3926 scenarios" — a pass/total ratio — from being
# read as a total claim about the 3925.
SCENARIOS = re.compile(r"(?<![/\d]\s)\b([\d,]{2,6})\s+(?:TCK\s+)?scenarios\b", re.I)


@dataclass(frozen=True)
class Check:
    name: str
    truth: Callable[[], int]
    pattern: Pattern[str]
    ground: str
    # Repo-relative path prefixes this check governs. Empty = every live doc.
    #
    # Needed because there are two TCK suites: "N scenarios" means the
    # openCypher suite in `crates/uni-tck/**` and the Locy suite elsewhere,
    # with different totals. Without scoping, one check's truth silently
    # grades the other's claims.
    paths: tuple[str, ...] = ()

    def governs(self, rel: Path) -> bool:
        return not self.paths or str(rel).startswith(self.paths)


CHECKS: list[Check] = [
    # Two things this must NOT flag:
    #   * subset counts — "the other 19 surfaces are Rust-only" is a correct
    #     statement about the non-portable remainder, not a claim about the total;
    #   * `surfaces` used as a verb — "line 561 surfaces the same error".
    # Requiring either the literal word `extension` or a preceding `all` picks
    # out the total-claiming phrasings and leaves both of the above alone.
    Check(
        name="plugin surfaces",
        truth=surface_count,
        pattern=re.compile(
            r"\ball\s+(\d{1,3})\s+surfaces\b|\b(\d{1,3})\s+extension\s+surfaces\b", re.I
        ),
        ground="assert_eq!(kinds.len(), N) in crates/uni-plugin/src/surfaces/mod.rs",
    ),
    Check(
        name="graph algorithms",
        truth=graph_algorithm_count,
        pattern=re.compile(r"\b(\d{1,3})\s+graph\s+algorithms\b", re.I),
        ground=(
            "const DISTINCT_ALGORITHMS in "
            "crates/uni-plugin-builtin/tests/builtin_register.rs"
        ),
    ),
    Check(
        name="openCypher TCK feature files",
        truth=tck_feature_file_count,
        pattern=FEATURE_FILES,
        ground="*.feature files under crates/uni-tck/tck/features",
        paths=("crates/uni-tck/",),
    ),
    Check(
        name="openCypher TCK scenarios",
        truth=tck_scenario_count,
        pattern=SCENARIOS,
        ground="expanded Scenario/Examples rows under crates/uni-tck/tck/features",
        paths=("crates/uni-tck/",),
    ),
    Check(
        name="Locy TCK feature files",
        truth=locy_tck_feature_file_count,
        pattern=FEATURE_FILES,
        ground="*.feature files under crates/uni-locy-tck",
        paths=("crates/uni-locy-tck/", "docs/complete_locy.md"),
    ),
    Check(
        name="Locy TCK scenarios",
        truth=locy_tck_scenario_count,
        pattern=SCENARIOS,
        ground="expanded Scenario/Examples rows under crates/uni-locy-tck",
        paths=("crates/uni-locy-tck/", "docs/complete_locy.md"),
    ),
    Check(
        name="skill reference files",
        truth=skill_reference_count,
        pattern=re.compile(r"\b(\d{1,3})\s+reference\s+files\b", re.I),
        ground="*.md under skills/uni-db/references",
    ),
]


def live_docs() -> list[Path]:
    out: list[Path] = []
    for root in DOC_ROOTS:
        for p in (ROOT / root).rglob("*.md"):
            rel = p.relative_to(ROOT)
            if any(part in EXCLUDED_PARTS for part in rel.parts):
                continue
            if "target" in rel.parts:
                continue
            out.append(p)
    return sorted(out)


def main() -> int:
    docs = live_docs()
    failures: list[str] = []
    checked = 0

    for check in CHECKS:
        want = check.truth()
        for path in docs:
            rel = path.relative_to(ROOT)
            if not check.governs(rel):
                continue
            for lineno, line in enumerate(path.read_text().splitlines(), 1):
                for m in check.pattern.finditer(line):
                    raw = next(g for g in m.groups() if g is not None)
                    got = int(raw.replace(",", ""))
                    checked += 1
                    if got != want:
                        failures.append(
                            f"{rel}:{lineno} claims {got} "
                            f"{check.name}, source has {want} ({m.group(0)!r})\n"
                            f"      ground truth: {check.ground}"
                        )

    if failures:
        print("Documented-count check FAILED:\n")
        for f in failures:
            print(f"  - {f}")
        print(
            "\nUpdate the prose, or update the pinned count if the thing it "
            "counts genuinely changed."
        )
        return 1

    counts = ", ".join(f"{c.name}={c.truth()}" for c in CHECKS)
    print(f"OK: {checked} documented count claim(s) match source ({counts})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
